# Example how can you include config.yaml in your provision scripts
# Ansible vault is better approach. https://docs.ansible.com/ansible/latest/user_guide/vault.html
- name: Load config.yml.
  include_vars:
    file: /vagrant/config.yaml
    name: config

- name: Create {{ config.ssh_user }} user
  user:
    name: '{{ config.ssh_user }}'
  become: true

- name: Add user "{{ config.ssh_user }}" to sudo
  lineinfile:
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html#parameter-path
    # path: "/etc/sudoers.d/vagrant"
    dest: "/etc/sudoers.d/{{ config.ssh_user }}"
    line: '{{ config.ssh_user }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
  become: true

- name: Set {{ config.ssh_user }} ssh ssh_key
  authorized_key:
    user: '{{ config.ssh_user }}'
    key: '{{ config.ssh_key }}'
  become: true
